### ISSUE TITLE
Asset license

### ISSUE THREAD

**Issue by Calinou** [emberhunt/emberhunt#36]
This project's assets are currently licensed under CC BY-NC-SA 4.0, which isn't a free culture license and has [many practical implications](https://freedomdefined.org/Licenses/NC). As an open source project, please consider using an asset license that respects the four freedoms such as [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by PonasKovas** [comment]
> has many practical implications

Could you give an example?

We wanted to make so that if you want to make your own version of the game, go ahead, you can use everything, but if you want to make money from your own version, you will have to make your own sprites and music, which seemed like a fair trade to us
